nodes:
  - input.visual:
      source:
  - model.yolo:
      detect:
        - person
        - cell phone
        - car
        - motorcycle
        - bus
        - truck
        - fire hydrant
        - tv
        - laptop
        - microwave
        - oven
        - toaster
        - refrigerator
        - hair drier

  - draw.bbox:
      show_labels: true
  - custom_nodes.output.media_writer_h264:
      output_dir: ../flask-server/staticimage.png
